### ISSUE TITLE
.net 4.6.1

### ISSUE THREAD

**Issue by davidtme** [fsprojects/Foq#7]
I’m just trying to upgrade a unit test project to .net 4.6.1 - I’m getting some very odd messages when trying to use Foq:

```
System.MissingMethodException : Method not found: 'Void Foq.Mock`1..ctor(Foq.MockMode, Microsoft.FSharp.Core.FSharpOption`1<Microsoft.FSharp.Core.FSharpFunc`2<System.Type,System.Object>>)'.
```

Before I go digging to much I just wanted to know if Foq is compatible with frameworks above v4.5

**Comment by ptrelford** [comment]
Short answer: Foq is compatible with .Net frameworks over v4.5, you probably have a different version of FSharp.Core & need to use binding redirects.
Longer answer:
The code in this github project was pulled over from the project's original home on codeplex (it's quite an old project), because people like GH, unfortunately the documentation wasn't pulled with it.
If you take a peek at the front page of http://foq.codeplex.com/ which has key usage instructions, there's advice on handling dependencies.
If you are seeing MissingMethodException most likely your project is binding to a different version of the FSharp.Core library to the one used by the Foq assembly you are referencing via a Nuget package or elsewhere. To work around this as per the instructions on the CodePlex site you either need to enable automatic binding redirects or manually set binding redirects. Sorry about that, unfortunately that's just an annoying thing with dependencies and versions on .Net which is particularly noticeable with F# due to it's update cadence, i.e. it updates every few months or so where the .Net framework historically has been every year or so.
Another option that you may want to consider if you're using a package manager like paket is simply to add the file Foq.fs to your test project and all the dll hell goes away.
